### ISSUE TITLE
Image edits from Telegram are not handled correctly

### ISSUE THREAD

**Issue by tulir** [mautrix/telegram#149]
~~Official clients probably don't support it,~~ but it's possible.

**Comment by JuniorJPDJ** [comment]
It's pretty common now to edit already sent images. Would be cool to have it fixed. Thanks for your development ;D

**Comment by tulir** [comment]
Image edits should work now since I changed the bridge to store the image event ID instead of the caption event ID. It means edited captions won't work, but that's hopefully less problematic.

There's also [a config option](https://github.com/mautrix/telegram/blob/44f2c648a83694c7b4591bdbb773a85d8bb7a6f1/mautrix_telegram/example-config.yaml#L209-L211) to send the caption as the `body` as per [MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
