### ISSUE TITLE
Telegram Groups-> Matrix /0 converted to !0

### ISSUE THREAD

**Issue by L0ric0** [mautrix/telegram#331]
as the title says a string in containing /[0-9] is converted to ![0-9] on the matrix side.
in personal chats this does not happen and a lone / is not converted.
Also there are no logs

**Comment by tulir** [comment]
It's technically a feature, the bridge replaces / with ! in anything marked as a command by the telegram server

**Comment by L0ric0** [comment]
but that doesn't seem to be consistent as i have in a private chat no replacement (and it is treated as a phone-number by telegram) and in a group chat the replacement (also treated as a phone-number)
