### ISSUE TITLE
/me is replaced with MXID instead of display name

### ISSUE THREAD

**Issue by pacien** [mautrix/telegram#348]
In chats created on the Matrix side, `/me` isn't properly substituted with the display name and is instead replaced with the user's MXID.

This problem doesn't affect chats initiated on Telegram's side, in which `/me` is correctly replaced with the user's display name.

Observed on v0.6.0.

**Comment by tulir** [comment]
This is a state cache bug. `!tg sync-state` in the problematic room should fix it
