### ISSUE TITLE
Hide homeserver token from aiohttp logs

### ISSUE THREAD

**Issue by pacien** [mautrix/telegram#351]
By default, the aiohttp logger is set to the INFO level, which causes all HTTP requests to be logged with the appservice's token in them. This might be a security issue.

For reference, Synapse redacts all tokens when logging requests.

**Comment by tulir** [comment]
Related to #321

**Comment by pacien** [comment]
An easy workaround could be to set this logger's level to WARNING by default instead.

https://github.com/tulir/mautrix-telegram/blob/281f7203dc6eec8be9e6489a8bf29ad7e850f07d/example-config.yaml#L345-L346

**Comment by tulir** [comment]
This should be fixed on the server side (matrix-org/matrix-doc#2832)
