### ISSUE TITLE
Implement ban/kick bot commands on Telegram bot side for Matrix users

### ISSUE THREAD

**Issue by MurzNN** [mautrix/telegram#357]
When we try bridge popular Telegram groups to Matrix via bot, very often group moderators refuse to do this, because they will have no functions for ban/kick Matrix users from Telegram side, and they don't want to use both clients (Matrix and Telegram) to fully moderate group.

For solve this problem, will be good to implement ban/kick commands on Telegram Bot side, that will allow moderation commands for Matrix users from Telegram side.

**Comment by MurzNN** [comment]
Here is similar feature request for Slack bridge https://github.com/matrix-org/matrix-appservice-slack/issues/116 and proposed solution is `/mx-ban` command

**Comment by JuniorJPDJ** [comment]
There could be /list command to list non-Telegram users in channel and /kick which could kick replied message author or use mxid to do so.
++

**Comment by why-not-try-calmer** [comment]
I believe #819 provides an elegant solution to this issue. The fact that it does not rely on printing a list of non-Telegram users in the channel makes it very easy to use (if I am getting this correctly, `/mxban` as sole content of a Telegram reply to a message forwarded by the bot and originally sent by the user to ban).

**Comment by why-not-try-calmer** [comment]
@tulir Hey mind to add a comment here? It's very much frowned upon to close PRs without explaining the author why, no matter how much you disagree with the PR.

**Comment by maltee1** [comment]
@why-not-try-calmer the issue is closed because an appropriate pull request has been merged, tulir mentioned the commit in the close message. I suppose that's a sufficient explanation.

**Comment by why-not-try-calmer** [comment]
@maltee1 My bad, for some reason the mobile version of GitHub had the commit collapsed for some reason. Thanks a lot! Also side question since I could not infer that from looking at your GitHub Actions: when is the commit due for staging and making it into the bot offered under https://t2bot.io/telegram/?

**Comment by maltee1** [comment]
if https://github.com/t2bot/mautrix-telegram is what t2bot is using, then it's massively outdated and much older than even the latest release of mautrix/telegram. I suggest you ask at t2bot.
As for when this will be part of a release, there is no release schedule and I suppose tulir doesn't know himself until shortly before ;)
