### ISSUE TITLE
Bridge reactions from/to Telegram

### ISSUE THREAD

**Issue by tulir** [mautrix/telegram#363]
Sources tell me Telegram is getting message reactions in the near future. The bridge should handle them in both directions. Most likely needs a new db table for storing ids.

**Comment by xhdix** [comment]
Now there are [reactions in Telegram](https://telegram.org/blog/reactions-spoilers-translations), but if someone has a reaction in Telegram, the original message will be deleted in Matrix.

**Comment by JuniorJPDJ** [comment]
Tbh I'd tag v0.11.1 with reactions, cause without reaction support bridge is editing message to empty when someone reacts using telegram client.

**Comment by fariszr** [comment]
looks like reactions don't work with a relay bot, you need a personal account linked

**Comment by JuniorJPDJ** [comment]
Yup. I can't imagine how relay bot could react multiple times for all users that reacted on matrix side.

**Comment by fariszr** [comment]
Sending the first reaction should be enough.

Whats more important is mirroring telegram reactions to matrix. Be it reactions to telegram messages or matrix messages.

**Comment by JuniorJPDJ** [comment]
Those are already mirrored on my groups.

**Comment by fariszr** [comment]
ok reactions don't work with a relaybot setup.

`Note that reactions from relayed users will not be bridged at all, because the bot wouldn't be able to bridge sender info nor multiple reactions of the same emoji.`

**Comment by JuniorJPDJ** [comment]
From telegram to matrix works in both setups.

From matrix to telegram doesnt work when user is not using login.

**Comment by fariszr** [comment]
> From telegram to matrix works in both setups.
> 
> From matrix to telegram doesnt work when user is not using login.

did you change anything in the settings ? it didn't work for me

**Comment by zaibon** [comment]
I just updated to v0.11.1 but I can't seem to get reaction working in either direction.
I'm not using relaybot. Are reaction only available on newly created rooms after the upgrade to v0.11.1 ?
