### ISSUE TITLE
Most part of messages from public telegram groups are not bridged to Matrix room via puppeted bridge

### ISSUE THREAD

**Issue by MurzNN** [mautrix/telegram#368]
After September 18, most of incoming messages from public telegram groups stops bridging to Matrix room via puppeted bridge at t2bot.io instance. I write about puppeted bridge, because there are no `@matrix_t2bot` bot on Telegram side in those groups (Telegram group admins don't want to see bots in his rooms). 

Before this date all works well, all messages successfully bridged to Matrix room without `@matrix_t2bot` as group member, so the problem is not with missed bot on Telegram side.

After September 18, most of messages from Telegram side stops delivering to Matrix room, delivered only join/leave events, my messages, replies to my messages, other bots messages, and messages from people, that replied to my messages earlier.

t2bot.io admin can't find any errors in logs, regarding to https://matrix.to/#/!mPYrVomQESEYWWudQw:matrix.org/$15698549421009OOHPM:t2l.io?via=t2bot.io&via=matrix.org&via=privacytools.io so maybe you, @tulir, as developer, have any ideas what can becomes wrong and how to debug this issue?

Here is list of rooms:
https://t.me/drupal_rus » #telegram_drupal_rus:t2bot.io
https://t.me/drupal_beginner » #telegram_drupal_beginner:t2bot.io
https://t.me/blender_ru » #telegram_blender_ru:t2bot.io

Rooms are public, so you can join to them for see the problem and investigate.

**Comment by MurzNN** [comment]
My messages, send from Matrix client (and from Telegram client too), are delivered normally to Telegram group, also replies to my messages in Telegram group are delivered to Matrix room too, but other messages - not.

**Comment by MurzNN** [comment]
Here is example of problem: https://matrix.to/#/!zEFKCmbdHJWBofsCoc:matrix.org/$156985913780246UZVUp:t2bot.io?via=ru-matrix.org&via=t2bot.io&via=matrix.org 
![image](https://user-images.githubusercontent.com/336662/65895990-0260e100-e3b5-11e9-9651-ab5d244f29b6.png)
Between two my messages there must be message from other user, here how this timeline looks on Telegram side:
![image](https://user-images.githubusercontent.com/336662/65896042-23293680-e3b5-11e9-8dd1-d96ee5c2119f.png)

**Comment by MurzNN** [comment]
Want to notice, that typing events from users are bridged well, so I see "User xxx is typing", but after this - his message are not shown on Matrix side.

**Comment by alien2003** [comment]
I have the same issues. Stopped using telegram because of that (I don't trust official app)

**Comment by tulir** [comment]
This might have been the lack of UpdatesTooLong handling in Telethon, which was fixed and is included in v0.12.0 of the bridge
