### ISSUE TITLE
New 1:1 chats not opening in Matrix

### ISSUE THREAD

**Issue by bnjbvr** [mautrix/telegram#372]
Hi there! Thanks for the great work done on this project. It seems new 1:1 conversations don't create a new room invitation in Matrix since I've updated to the latest version. I suspect latest commit on master fixes it, so it might be just a need to bump the version number / update the Docker image (I'm using Docker!). Please let me know if I can help in any ways, and keep up the great work!

**Comment by akhilman** [comment]
I have same problem with @telegram:t2bot.io 
mautrix-telegram 0.7.0+dev.234eec1f
