### ISSUE TITLE
add configured community to m.room.related_groups retroactively

### ISSUE THREAD

**Issue by lub** [mautrix/telegram#441]
Currently you can configure a community in the config.yaml and it gets added to m.room.related_groups during portal creation.

But if you configure the community only after initial portal creation the existing rooms don't get the m.room.related_groups event necessary for displaying flairs.

Version: v0.7.2-rc1

**Comment by IngwiePhoenix** [comment]
Seconded. I am currently structuring all my bridges into communities for an easier overview in Riot. Would definitively appreciate this feature as well!

**Comment by tulir** [comment]
@IngwiePhoenix Note that `appservice` -> `community_id` only sets a flair for bridged users, it doesn't add rooms to any community (that's the `community_template` feature)

**Comment by ChrisLane** [comment]
@tulir does this `community_template` feature exist yet?
I'd like to be able to keep all my telegram chats separate for others

**Comment by shukon** [comment]
@ChrisLane that's kinda what #365 is about, right?
