### ISSUE TITLE
Correctly bridge profile change events M->T

### ISSUE THREAD

**Issue by ludwigbald** [mautrix/telegram#460]
I have not logged into Telegram, so the relay bot posts stuff.

When changing my matrix display name, it sends "**Ludwig** joined the room", instead of "**oldname**'s display name is now **Ludwig**"

When changing my profile picture, it sends "**Ludwig** joined the room" again, instead of saying nothing, as it can not reasonably convey the change.

**Comment by tulir** [comment]
This is probably a synapse bug: matrix-org/synapse#4268

**Comment by MaximilianGaedig** [comment]
This happens on dendrite to me, maybe it is a bridge bug? Other bridges certainly don't have this problem
