### ISSUE TITLE
Preserve message order when bridging from Telegram to Matrix

### ISSUE THREAD

**Issue by tulir** [mautrix/telegram#505]
Currently the bridge processes incoming messages in parallel and doesn't care about message order at all. This means that groups of forwarded messages, image albums and even normal messages may be bridged to Matrix out of order.

The solution is enabling `sequential_updates=True` in `TelegramClient`, but before that, media uploads need to become asynchronous (so that a big file being bridged doesn't block all other messages). Asynchronous media uploads while preserving message order requires matrix-org/matrix-doc#2246.

**Comment by JuniorJPDJ** [comment]
What if you just edit message after sending a file?
It would probably break other things like facebook bridging, but it seems like pretty good workaround.
