### ISSUE TITLE
Images with captions don't store Matrix event ID of caption

### ISSUE THREAD

**Issue by tulir** [mautrix/telegram#511]
Currently the database can only store one event ID per Telegram message (except for edits). However, images with captions are bridged as two messages. This means that:

* Replying to the image event from Matrix won't be bridged correctly
* Deleting the image event from Matrix won't be bridged correctly
* Deleting the message from Telegram will only delete the caption

Bridging image messages as inline images is already supported by the bridge, but not supported by most clients. The preferred solution would be implementing matrix-org/matrix-doc#2530 everywhere, but alternatively the database could be updated to support a many-to-one mapping.

**Comment by JuniorJPDJ** [comment]
What about albums which are also being bridged as 1 telegram message to many matrix messages?

**Comment by tulir** [comment]
Albums are many messages on telegram
