### ISSUE TITLE
Message I write in Telegram appear has "Encrypted by unverified session" in Matrix

### ISSUE THREAD

**Issue by celogeek** [mautrix/telegram#578]
I installed synapse 1.24, with mautrix-telegram master branch (of yesterday).

I setup double puppet.

When I send a message from Telegram client, the message appears with the "Encrypted by unverified session" in Matrix.
When I send photo/video, those appear with the Red crypto icon in Element Desktop, and don't appear at all in the Element IOS version (guess it does not allow every unverified messages ?)

I can see an unverified session in the settings, but I can't validate it (error appear).

Do you have this problem ? How can I fix this ?

Thanks.

**Comment by tulir** [comment]
It's not a problem
