### ISSUE TITLE
Telegram Replies Don't Work In Element Mobile App

### ISSUE THREAD

**Issue by WardenTechServices** [mautrix/telegram#579]
Hello,
I have used spantaleev/matrix-docker-ansible-deploy to deploy and set up matrix and element and mautrix-telegram. I have found an issue where it won't show the replies for users to messages on the mobile version of Element. I have tried it unencrypted and encrypted. It does work on the web version and desktop version of Element. It does work if you reply it will show up. It is only when someone replies to your message that it doesn't show up in the app. I was wondering if it is a limit of mautrix-telelgram or if it is something I need to open an issue for in the Element app on Github.

**Comment by tulir** [comment]
Element mobiles don't support replies: vector-im/element-android#174
