### ISSUE TITLE
Tell people how to add to Telegram

### ISSUE THREAD

**Issue by danshearer** [mautrix/telegram#606]
A bridge has two sides but you only talk about one of them :-)

The [telegram bridge docs](https://matrix.to/#/#telegram:maunium.net) don't tell me anything about how to access a matrix room from the Telegram side, nor the docs here on Github. I'm sure I'll figure it out. But it would be helpful.

Thanks for the code, I'm sure I'll be using the bridge any time soon,

**Comment by olmari** [comment]
You don't access matrix-room from telegram side, that kind of functionality is not possible on telegram. an matrix-(group-)room is needed to be bridged onto telegram group very manually, and then said room is bridged. Generally there is nothing anyone can do in order to make pure telegram side to do anything with pure matrix side.

**Comment by olmari** [comment]
Flow is that (and/or logic) user login to telegram withing matrix with bridge, and then one can use telegram through matrix and/or an telegram group is bridged to matrix room and then users can talk with eachothers in that room as best as tech allows (telegram users seen as puppets on matrix side, non-logged in (to telegram) users in matrix is seen as bridge relaying messages.

**Comment by danshearer** [comment]
Ah I see. I';m an occasional Telegram user and I thought it would be a quick way of hooking people up to Matrix who haven't heard of any of these technologies.

Therefore, my original plan is the only plan, which is to run my own project-specific Matrix node with all the gateways and integrations I want my users to have. 

Thanks, that helps. And might be a good idea to put into the docs :-)

**Comment by olmari** [comment]
Generally no "alien" IM support anything alike, while matrix has been thought from ground up to make such thing possible, hence generally impossible thing to do with any other network while it works from matrix to other networks as it is.

**Comment by JuniorJPDJ** [comment]
@olmari XMPP also supports similar thing, but matrix did it muuch better ;)
