### ISSUE TITLE
Config comment is getting duplicated on every bridge restart

### ISSUE THREAD

**Issue by JuniorJPDJ** [mautrix/telegram#633]
Hi!
This bug is old and afair @wvffle have it too.
When I restart bridge I'm having this:
```
$ git diff
diff --git a/data/mautrix-telegram/config.yaml b/data/mautrix-telegram/config.yaml
index 56e1c47..5507a4b 100644
--- a/data/mautrix-telegram/config.yaml
+++ b/data/mautrix-telegram/config.yaml
@@ -393,6 +393,8 @@ bridge:
         - 1121665074
         - 1410674750
 
+    # The prefix for commands. Only required in non-management rooms.
+
     # The prefix for commands. Only required in non-management rooms.
     command_prefix: '!tg'
```
Like every restart from near a year.
It duplicates and duplicates and file size is getting sick.
It's always the same comment, never had similar issue with other one.

**Comment by wvffle** [comment]
I removed the duplicated comments a few months ago and I've just checked, I don't have it anymore.

**Comment by JuniorJPDJ** [comment]
I'm still getting them after bridge restart.

**Comment by JuniorJPDJ** [comment]
It seems to be caused by map-in-map a bit above this comment.
When I added fake config line above comment - this comment didn't get cloned.
Bridge removed this line automatically tho, so it's not permanent workaround.

I'll try moving some values in place.

**Comment by JuniorJPDJ** [comment]
When I moved `management_room_text` value from below to upper of `command_prefix`:
1. bridge cloned a comment above new value
2. bridge moved it back to the place

I was left with this:
```diff
+++ b/data/mautrix-telegram/config.yaml
@@ -387,6 +387,9 @@ bridge:
         - 1121665074
         - 1410674750
 
+    # Messages sent upon joining a management room.
+    # Markdown is supported. The defaults are listed below.
+
     # The prefix for commands. Only required in non-management rooms.
     command_prefix: '!tg'
 ```
