### ISSUE TITLE
Improve robustness and transparency of errors

### ISSUE THREAD

**Issue by theCalcaholic** [mautrix/telegram#637]
Often when there are exceptions within my telegram (or probably any) bridge, it just silently fails and I don't receive any message or my messages aren't forwarded. In some cases, the synchronization of a whole chat might even be broken.

It would be preferable to catch these exceptions and show an error message to the user - ideally with an instruction on how to report it.
Depending on the configuration, the error message could contain the stack trace - maybe encrypted for a key held by the administrator - to simplify reporting these exceptions.

If you think, this is a good idea, I'd be willing to give this a try myself.

**Comment by tulir** [comment]
Errors are already reported to the user (if the bridge is configured to do so)

**Comment by theCalcaholic** [comment]
In that case it might just be a matter of a few missing try..catch clauses :)

Some exceptions are definitely not being reported
