### ISSUE TITLE
Messages sent from Telegram clients don't show up on Element within DMs.

### ISSUE THREAD

**Issue by iisharankov** [mautrix/telegram#654]
If i send a message to someone via a matrix client (mine is element), it gets sent to the chat and I see it in the Telegram client. But any time I send a message from Telegram to a user, it does not appear on Element. I also get the following log in the docker-compose logs:

```
mautrix-telegram    | [2021-08-12 10:26:10,172] [DEBUG@mau.portal.SOMENUMBER<->SOMENUMBER] Ignoring private chat message SOMENUMBER@SOMENUMBER as receiver does not have matrix puppeting and their default puppet isn't in the room
```

Shown as images:
What Element sees:
![image](https://user-images.githubusercontent.com/30711273/129183539-40f3e34c-9494-43a4-adad-dcf9655cf59e.png)

What Telegram sees:
![image](https://user-images.githubusercontent.com/30711273/129183518-684eb39c-bfe2-443d-b706-0d7d99f64597.png)

I'm fairly certain the issue is in the config.yaml file, but I've combed through it for an hour and googled this problem and nothing comes up. All the default changes to the config that you need to set up are correct, and nothing else was touched. 

All other messaging (groups, sending messages from element, receiving from others) works perfectly, but messages from the Telegram client are not seen on element _for me_.

Some extra quirks I've noticed: 

1. Interestingly, sending messages to "Saved Messages" with Telegram does show up on Element, but all other DMs do not.
2. I've tested this with another user who has a Telegram bridge bot and their Element instance *does* see my messages sent via the Telegram client, but mine does not.
3. If I DM a person in Telegram that I have not started a chat with in Element yet, I still get invited to the room, but the message I sent them to trigger the invite does not show.

This all has to do with that docker log error above, but I can't find out what's the cause of it.

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/general/double-puppeting.html

**Comment by iisharankov** [comment]
Oh, so that's what double puppeting was on about. My bad / thanks!
