### ISSUE TITLE
Leave a Portal Room without leaving the matrix channel

### ISSUE THREAD

**Issue by derhagen** [mautrix/telegram#658]
Hi there, I don't need all of my Telegram groups to be bridged to matrix. I figured out that leaving a room in Matrix makes my Telegram account leave the respective Telegram group (see https://github.com/mautrix/telegram/issues/28). 

However, I could not figure out how to remove a room from Matrix while staying a member of the Telegram group. `!tg unbridge` seems to do something else.

Edit: Unbridge might exactly be what I'm looking for, but even though I'm the only Matrix user in the whole room, it says `You do not have the permissions to unbridge that portal.`. Probably because the bridge bot is the only group admin

**Comment by tulir** [comment]
Unbridging checks bridge permissions in addition to room permissions, you should just make yourself bridge admin. Make sure you also add it to the filter list to prevent the bridge from re-creating the portal next time there's a message.
