### ISSUE TITLE
No connection matrix to telegram

### ISSUE THREAD

**Issue by chagai95** [mautrix/telegram#659]
Not seeing any exception in the logs and nothing else suspicious...

All functionality which involves messages written from the telegram client work properly but if I write anything on the matrix side nothing gets mapped to telegram:
1. Double puppets messages don't work.
2. Ping or any other commands don't work.
3. Relaybot messages don't work

**Comment by chagai95** [comment]
Working again, after a while it just started working again, very weird, no idea why...

**Comment by sumnerevans** [comment]
Sounds like you figured this out. Feel free to reopen if this is still an issue, but please add more debugging details.
