### ISSUE TITLE
Ability to disable direct messages

### ISSUE THREAD

**Issue by kosciak9** [mautrix/telegram#665]
Hello,

At our server we have bridge to external group (TG) where other members of our project reside. I wanted for our users to be double puppeteer-ed (it's cleaner), so I asked them to login. Unfortunately, it's generating a lot of noise with their direct messages. Is there a way to keep double puppeteering and lose direct messages? I've been looking for solution for quite a long time and found nothing (filters don't matter for direct messages).

I could maybe try to look into code and prepare a PR, but I'm not sure how you want to proceed here.

Thanks in advance

**Comment by kosciak9** [comment]
Possibly - just disable recreating chats that were closed when new message arrives in those chats. I keep on deleting direct messages, they're forgotten - and then recreated shortly afterwards.

**Comment by Ultrawipf** [comment]
Would be very nice to change per user during the login if they only want to only act in manually bridged channels or receive their whole telegram activity with private messages. Or disable auto generated channels completely and only use manual bridging.

Maybe i am missing something but i haven't seen an option yet to be logged in and not get spammed by telegram events in matrix.
