### ISSUE TITLE
Bad search accuracy due to "(Telegram)" suffix

### ISSUE THREAD

**Issue by derhagen** [mautrix/telegram#678]
When searching for a telegram user to start a new chat like `search Tom Hanks`, the search accuracy is very bad, since mautrix-telegram compares the search query with the name list including the appended "(Telegram)" (By Levenshtein distance or something similar I assume). So, even if I know the name exactly, I often only get 60% matches. With a bit of bad luck, your desired Person is not even in the list you are presented.

**Comment by tulir** [comment]
This might be fixed on the master branch now
