### ISSUE TITLE
Telegram user invited to space

### ISSUE THREAD

**Issue by lugino-emeritus** [mautrix/telegram#682]
I invited some telegram users to a space. After a week I realized that I was not able to write to one of them. Looking into the database I realized that the direct chat of this user was mapped to the space. Probably this was the first user the client invited into the space. Hence you should not invite telegram users to spaces.

Version: 0.10.1 (release)
Steps to reproduce: Create a space, then invite a telegram user.
You can see in the portal table that the user is mapped to the space now.

**Comment by tulir** [comment]
Don't do that

**Comment by JuniorJPDJ** [comment]
This probably should be blocked in bridge. I'd not close this.
