### ISSUE TITLE
alembic_version table not found psycopg2.errors.DuplicateTable: relation "portal" already exists

### ISSUE THREAD

**Issue by poltrian** [mautrix/telegram#691]
When i run alembic upgrade head ist shows alembic_version table not found psycopg2.errors.DuplicateTable: relation "portal" already exists
 when i try to start `[CRITICAL@mau.init] alembic_version table not found. Did you forget to `alembic upgrade head`?`
How can i fix it?

**Comment by tulir** [comment]
Don't use a database with other things in it

**Comment by LotharMadsson** [comment]
I am having the same problem. The documentation is not very precise about it and your answer @tulir either. 
Do I have to define a different database in den config under database? In the case of the signal bridge it was enough to insert the URI of the default database of my synapse server.
Could you elaborate on that?
