### ISSUE TITLE
ads are required

### ISSUE THREAD

**Issue by rakshazi** [mautrix/telegram#699]
Hello,

Seems like Telegram will require 3rdParty apps to support and display their ads very soon: https://corefork.telegram.org/api/sponsored-messages#sponsored-messages-in-third-party-apps

I think that bridge can be considered as a third party telegram client, so it should support ads as well

**Comment by jaywink** [comment]
Just got this message regarding a bridge app:

> Dear developer,
> 
> Telegram continues to grow worldwide, in part thanks to your third-party app. If your app is built from your own code, you'll need to make two changes so your users can keep chatting. If you are using the up-to-date open source code for one of our apps, these changes have already been made.
> 
> Support for int64 IDs
> With its rapid growth, Telegram is moving from 32-bit to 64-bit IDs so that users can continue creating billions of groups, channels and bots. Your app will need to support these new IDs as soon as possible to ensure users aren't interrupted.
> 
> To do so, make sure your app supports this API layer: https://core.telegram.org/api/layers#layer-133
> 
> Sponsored Messages
> To cover its growing infrastructure costs, Telegram added sponsored messages – a paid, privacy-friendly way to promote bots and channels. We are happy to see support for this has already been added across the majority of third-party apps.
> 
> We ask that you make sure that these sponsored messages are supported and properly displayed in your app by January 1, 2022. Unfortunately, Telegram cannot financially sustain apps that support Telegram Channels but do not display official sponsored messages – such apps will have to be disconnected.
> 
> The necessary methods for this change are available here: https://core.telegram.org/api/sponsored-messages
> 
> You can read more about sponsored messages here: https://t.me/durov/172
> 
> Telegram's API usage will continue to be free of charge for all developers. We're counting on your understanding and support so that Telegram and your app can continue to offer private, secure messaging to people around the world.
> 
> The Telegram Team
