### ISSUE TITLE
Bot joined multiple public rooms on my server without any reason

### ISSUE THREAD

**Issue by krillefear** [mautrix/telegram#700]
Hey there, I have tried to install the mautrix-telegram bot for my private homeserver. The weird thing is, that the bot once I had configured it, has started to join random public rooms which are known on my servers. The logs got flooded with events. I assume that I have messed up the configuration somehow but I have just changed what was necessary from the defaults like the homeserver domain, the appid and apphash of my telegram API and the permissions which I set to that all users on my homeserver have full permissions and my matrix ID has admin permissions.

So if I have messed up the configuration, I would like to know how and a warning in the docs would be nice :-D

**Comment by tulir** [comment]
Did you mess with the registration file? If the `namespaces` don't have the server name in the regex, synapse would forward events from any telegram-bridged room (even bridged by other servers) to the bridge, which would cause the bridge to join the rooms
