### ISSUE TITLE
"Unsupported User" on Matrix side

### ISSUE THREAD

**Issue by z3ntu** [mautrix/telegram#705]
![image](https://user-images.githubusercontent.com/3768500/144750998-f9c4d68b-d71e-4b3a-aa17-737b1b265af8.png)

From the Telegram side it's a completely normal user with a name and no profile picture.

**Comment by tulir** [comment]
The avatar seems to already specify what to do

**Comment by z3ntu** [comment]
So t2bot has to update their mautrix-telegram version?

**Comment by steadfasterX** [comment]
Hmm i have updated ykur bridge 4 days ago and still have that issue @tulir .. I followed the steps in your guide abd restarted synapse and the bridge ofc..
