### ISSUE TITLE
Log in as primary device?

### ISSUE THREAD

**Issue by IngwiePhoenix** [mautrix/telegram#711]
Hello!

Very quick question: Can this bridge also log in as the primary device? I could not find any kind of statement making this clear.

Thank you and have a great day - also thank you so much for this bridge. Been using it since a very long time now (might actually be a year, but i would've have to double check) and it's been awesome!

**Comment by tulir** [comment]
Telegram doesn't have the concept of primary or secondary devices (because there's no encryption like on WhatsApp and Signal)

**Comment by IngwiePhoenix** [comment]
So if I removed Telegram from my phone, the bridge would still function as intended? I didn't know. Thats really good to know.

Thank you!

**Comment by JuniorJPDJ** [comment]
Yes.
