### ISSUE TITLE
Telegram ban me after i link bridge

### ISSUE THREAD

**Issue by pilikan33** [mautrix/telegram#712]
Telegram ban me after i link bridge  -- WHHY ????

**Comment by pilikan33** [comment]
10 Telegram accounts were blocked forever thanks to your bridge

**Comment by JuniorJPDJ** [comment]
???

**Comment by pilikan33** [comment]
It turned out to be about the IP of the server - Bulgaria. Would you make a checker or a recommendation - because Telegram bans accounts without asking the last name and there can be valuable contacts
