### ISSUE TITLE
Configuration error: appservice.database not configured

### ISSUE THREAD

**Issue by NoverNobida** [mautrix/telegram#716]
I always got this error:
```
[CRITICAL@mau.init] Configuration error: appservice.database not configured
```
I run  
```
docker run --rm -v `pwd`:/data:z dock.mau.dev/mautrix/telegram
```
and edit it set  `SQLite:  sqlite:///data/tg.db`
run
```
docker run --rm -v `pwd`:/data:z dock.mau.dev/mautrix/telegram
```
again,
but still got this error.

**Comment by tulir** [comment]
As the error message says, you didn't configure (change) the `appservice` -> `database` field.

**Comment by NoverNobida** [comment]
I mean, I've edit it.
![图片](https://user-images.githubusercontent.com/46912250/147584509-8483cda4-f0d0-4448-815f-461a1972b4f7.png)
however  after running 
```
docker run --rm -v `pwd`:/data:z dock.mau.dev/mautrix/telegram
```
I got error `[CRITICAL@mau.init] Configuration error: appservice.database not configured`
and `config.yaml`  changed back to the way it was.
![图片](https://user-images.githubusercontent.com/46912250/147584766-22f3d204-9f57-4696-8e40-abb5adc71038.png)
and the others `haven’t` changed back.

**Comment by sumnerevans** [comment]
You did it wrong. You have to do:

```
database: sqlite:///filename.db
```

**Comment by NoverNobida** [comment]
@sumnerevans Thanks for the help! solved. I'm really careless.
