### ISSUE TITLE
SQLite optional dependency in Docker image?

### ISSUE THREAD

**Issue by FlyveHest** [mautrix/telegram#717]
I am using the Docker image, do I have to roll my own image to include the optional SQLite dependency?

I can't see it mentioned in neither requirements.txt or in the Dockerfile used to build your image itself.

**Comment by tulir** [comment]
It's documented in the docs https://docs.mau.fi/bridges/python/optional-dependencies.html

![image](https://user-images.githubusercontent.com/4224639/147564827-dd3769c5-8f54-4c0f-88d7-6e05d2ab860a.png)
