### ISSUE TITLE
Hashtags from telegram are unreadable in dark mode

### ISSUE THREAD

**Issue by artevaeckt** [mautrix/telegram#729]
Hashtags bridged from Telegram to matrix use a blue font, making them hard to read or even unreadable on dark backgrounds like in the Element dark mode since there is not enough contrast.

Since the corresponding event sources have entries like `"formatted_body": "<font color='blue'>#tag</font>"` I suspect mautrix-telegram to directly insert the font color. 

It would be nice to change the color to one that works well with different backgrounds or to get rid of the color.

**Comment by JuniorJPDJ** [comment]
getting rid of color seems good idea tbh, why is it there at the first place?
