### ISSUE TITLE
Voice messages forwarded Matrix->Telegram as non-playable file

### ISSUE THREAD

**Issue by JuniorJPDJ** [mautrix/telegram#732]
Hello!

It was nice to see voice messages forwarded from Telegram to Matrix as native matrix voice messages.
The last voice message problem I can think of is that Matrix-native voice messages are forwarded to Telegram as non-playable file.
![image](https://user-images.githubusercontent.com/7334549/148550174-96ea3aa7-2f9d-45d3-b3b4-192d59c9b0d4.png)
Another way works very good :D

**Comment by tulir** [comment]
Voice messages are working correctly in both directions

**Comment by JuniorJPDJ** [comment]
Those are sent to the telegram as file, not as voice message.
This for example makes them unplayable on Telegram macOS.
I need to download them and open in media player.

Next screenshots from now (running latest master build) using Element Android and Telegram-FOSS:
Voice message was uploaded by Element.

![image](https://user-images.githubusercontent.com/7334549/148603711-1e5be0ca-2d2b-446b-9b24-b6beafa51e23.png)
![image](https://user-images.githubusercontent.com/7334549/148603770-4f40dbc3-6034-451e-b6fe-13cde921779f.png)
