### ISSUE TITLE
"Restrict saving content" causes the bridge to not proxy messages

### ISSUE THREAD

**Issue by turt2live** [mautrix/telegram#734]
![image](https://user-images.githubusercontent.com/1190097/148659757-87fd9b11-620a-449c-9d75-9a600dab6528.png)

This setting appears to cause the unsupported event error:
> This message is not supported on your version of Mautrix-Telegram. Please check https://github.com/mautrix/telegram or ask your bridge administrator about possible updates.

Turning it off (default) fixes the issue.

Unclear on what the logs for the bridge say - they go a bit too quick for my instance :)

**Comment by tulir** [comment]
Looks like it only happens on outdated bridges. Even v0.11.0 should work, but I'll release v0.11.1 some time soon

**Comment by turt2live** [comment]
I can still reproduce this on v0.11.0 - will try when v0.11.1 is out though.
