### ISSUE TITLE
Somehow the bridge used a space room ID for one of my portals instead of the real room ID 

### ISSUE THREAD

**Issue by chagai95** [mautrix/telegram#746]
One of my chats in Telegram was not being bridged, so I searched for the message and saw something weird happening - I then checked the database and saw that the ID of a space was in the portal row (a space that has that room) instead of the actual room.

Here is a video showing this:
https://chagai.website/using-space-instead-of-actual-room.mp4

I then changed the row to the right room ID and now it works again. 

(used this command - it's a bit weird because of the docker setup but you can see the UPDATE:
docker exec -it matrix-postgres psql -U matrix -d matrix_mautrix_telegram  -c "UPDATE portal SET mxid='"'!'"KaCEJIESDMQZVXszwf:chagai.website' WHERE mxid='"'!'"DbBCmzkbEWdxOpOtAl:chagai.website';"
)

Sorry if this is not related to the Telegram bridge but my first guess would be it is.

**Comment by tulir** [comment]
Don't invite bridge users to spaces
