### ISSUE TITLE
Matrix -> Telegram read receipt not working

### ISSUE THREAD

**Issue by GrandChaman** [mautrix/telegram#756]
Heya!

Thanks for this great tool!

I just have a small issue regarding the read receipt from `matrix` to `telegram`, they don't seem to work for me.
Is there a way I could debug that ?

**Comment by tulir** [comment]
[Double puppeting](https://docs.mau.fi/bridges/general/double-puppeting.html) or MSC2409 ephemeral events (also mentioned in the double puppeting docs) need to be enabled to bridge things like read receipts and typing notifications.
