### ISSUE TITLE
alembic upgrade head: FAILED: No config file 'alembic.ini' found, or file has no '[alembic]' section

### ISSUE THREAD

**Issue by xaionaro** [mautrix/telegram#758]
I'm trying to upgrade the DB schema. And I see [the official documentation](https://docs.mau.fi/bridges/python/telegram/dbms-migration.html) recommends to use `alembic upgrade head` for that. But it does not work:
```
bridges@dx-matrix:~/mautrix-telegram$ source ./bin/activate
(mautrix-telegram) bridges@dx-matrix:~/mautrix-telegram$ alembic upgrade head
  FAILED: No config file 'alembic.ini' found, or file has no '[alembic]' section
```

**Comment by tulir** [comment]
That page is for migrating between different DBMSes, not for upgrading the schema. Also as the page says, the script was removed in v0.11.0

**Comment by xaionaro** [comment]
> That page is for migrating between different DBMSes, not for upgrading the schema.

Yes, but I understand this is the part with `dbms_migrate`, while I assume `alembic` exists to upgrade schemas.

@tulir : Could you advise how to upgrade schema then?

**Comment by tulir** [comment]
> Could you advise how to upgrade schema then?

Just run the bridge
