### ISSUE TITLE
Missing telemetry documentation

### ISSUE THREAD

**Issue by qub1750ul** [mautrix/telegram#760]
I have an installation of mautrix-telegram that regularly goes down.
I wanted to connect the bridge to Prometheus to be promptly notified when that happens, but i'm not finding any docs about doing that, even tough i've seen claims in other issues about Prometheus metrics being available.

**Comment by tulir** [comment]
https://github.com/mautrix/telegram/blob/master/mautrix_telegram/example-config.yaml#L90-L93 is basically all the documentation. Custom metrics aren't documented, but the standard prometheus python metrics are probably enough to detect the bridge going down.

Looking at the logs might be more useful to find out why it's going down though
