### ISSUE TITLE
Support reactions for channel messages

### ISSUE THREAD

**Issue by andrigamerita** [mautrix/telegram#777]
Telegram supports anonymous reactions for messages sent in channels that enabled the feature, not only in group chats. The puppeting bot should support those correctly too, in the virtual rooms created by the bridge.
At the time of writing this, my homeserver is running the bridge version that 2 days ago was the latest from Docker.

The feature currently doesn't work as expected:
- Reacting on Matrix (or removing the reaction) to a message posted in a Telegram channel where the user is admin correctly performs the action
- Reacting on Matrix to a message posted in a Telegram channel where the user is not an admin is impossible, because the Matrix room gives no reaction sending permission to the user: a solution to the problem would be for the bot to simply give that permission to the user in the room
- Reacting on Telegram (or removing the reaction) doesn't sync the action on Matrix, probably because to the bot there is no user performing the action, since as we said they are anonymous and the Telegram API only tells that the message reactions have changed, not that a particular user has added or removed a reaction: the bot should be able to correctly handle this and maybe assign the action of adding/removing the reaction on the Matrix side to the "Telegram bridge bot" user itself

**Comment by tulir** [comment]
Matrix doesn't have any kind of anonymous reactions

**Comment by hermann-san** [comment]
It's true that reactions in Matrix are not anonymous,
However, It would still be useful if reactions would be transferred from matrix to Telegram , even if its not possible to other way around.
