### ISSUE TITLE
User who left the telegram chat still hangs out in the matrix chat

### ISSUE THREAD

**Issue by ShadowJonathan** [mautrix/telegram#779]
Recently on t2bot.io I encountered a user whom was still inhabiting the matrix side of the bridge, but who had long left the actual telegram chat;

![image](https://user-images.githubusercontent.com/22740616/161395261-e69b7a89-8758-4b04-ae59-5e46abda5942.png)
![image](https://user-images.githubusercontent.com/22740616/161395264-ec90839b-0f11-4264-8c79-234a584ffe21.png)
![image](https://user-images.githubusercontent.com/22740616/161395271-9db2caca-c2c3-47cf-9da7-8e523116e721.png)

The room where this happens is https://matrix.to/#/#waydroid:connolly.tech, and the powerlevels state is this;

<details>
<summary>Powerlevels</summary>

```json5
{
  "content": {
    "ban": 50,
    "events": {
      "m.room.avatar": 50,
      "m.room.canonical_alias": 50,
      "m.room.encryption": 100,
      "m.room.history_visibility": 100,
      "m.room.name": 50,
      "m.room.power_levels": 100,
      "m.room.server_acl": 100,
      "m.room.tombstone": 100
    },
    "events_default": 0,
    "invite": 50,
    "kick": 50,
    "redact": 50,
    "state_default": 50,
    "users": {
      "@caleb:connolly.tech": 100,
      "@cyjan:mrcyjanek.net": 100,
      "@telegram:t2bot.io": 50
    },
    "users_default": 0
  },
  "origin_server_ts": 1627654952212,
  "sender": "@cyjan:mrcyjanek.net",
  "state_key": "",
  "type": "m.room.power_levels",
  // ...
}
```

</details>

I know t2bot.io != Mautrix, but Travis said this is a bridge bug, it seems the bridge isn't properly "cleaning up" the room periodically, especially if a user is constantly changing their displayname like this.

**Comment by tulir** [comment]
Telegram doesn't tell anyone when users leave chats, so there's no way to bridge it. #140 is for resyncing the whole member list through the relaybot, although that won't work either if the bridge is configured to not sync all members into Matrix (which is very likely the case on t2bot.io)
