### ISSUE TITLE
How do I invite matrix users to join my tg group and read only?

### ISSUE THREAD

**Issue by moeik** [mautrix/telegram#786]
Every time the invitation to enter the room is always kicked out of the room by the bridge

**Comment by moeik** [comment]
How to use /invite? Please

**Comment by tulir** [comment]
You can remove kick permissions from the bridge bot. Other than that, there's no supported read-only mode, only read-write (with the [relay bot](https://docs.mau.fi/bridges/python/telegram/relay-bot.html))

**Comment by moeik** [comment]
> 
What is the exact command? Thanks
