### ISSUE TITLE
Bridge reactions also from relay bot and not only with double puppet mode 

### ISSUE THREAD

**Issue by chagai95** [mautrix/telegram#792]
I noticed that this does not happen for messages coming from the relay bot, I understand that it is probably useless from Matrix to Telegram (just show it as if coming from the bot?)  but from Telegram to Matrix it makes sense no? or is this not possible via the bot functionality and would have to be implemented via a telegram user, similar to WhatsApp/Signal?

**Comment by hermann-san** [comment]
I guess the matrix bot doesn't know from whom the reaction come's from in Telegram.

**Comment by tulir** [comment]
The bridge already supports bridging them, but Telegram doesn't send reactions to bots

**Comment by alfredonodo** [comment]
Hi,
you can vote this https://bugs.telegram.org/c/16089
