### ISSUE TITLE
Display name changes from telegram contact name to telegram username

### ISSUE THREAD

**Issue by reformedp** [mautrix/telegram#796]
I am self-hosting a matrix server to bridge different platforms, I am the only user on the platform. This issue has occurred with more than one of the bridged chats, long after the chat has been created on matrix.
```
[telegram name as saved in contact book] (Telegram) changed their display name to [name registered with telegram] (Telegram)
```
For example:
```
Dad (Telegram) changed their display name to John Doe (Telegram)
```
This problem occurs randomly as far as I can tell. I have used the default settings for the display name config.

Separately, I have tried to use set-displayname command as a workaround, but I have gotten the
```
That command is limited to bridge administrators.
```
message. How do I set myself as a bridge adminstrator?

Thank you.

**Comment by tulir** [comment]
That's the expected behavior unless it's changing the name back and forth.

Bridge permissions are located in the config: https://github.com/mautrix/telegram/blob/v0.11.3/mautrix_telegram/example-config.yaml#L404-L419

**Comment by tulir** [comment]
Option to use contact names was added recently (only for single-user instances, trying to use it on multi-user instances will cause names to flip back and forth)
