### ISSUE TITLE
Bridge freezes after a minute of work

### ISSUE THREAD

**Issue by JuniorJPDJ** [mautrix/telegram#809]
Hi,
Today I updated bridge (I'm using master branch) and bridge freezes after a minute from restart.
Last log message seems to be not related to the freeze.
Last image i used and it was working correctly were 5 days old sha256:aad2827b27b23d31e5aa75fcd3f83cd1a9954762518b44c0a8ef461939249501, now I'm using image with tag latest (sha256:33f6fbd8f736167c2da51c9bf78628a17388a19750b62792b58054f66cfdeb38).

I'm unable to downgrade to last working version due to DB schema mismatch (my bad, I didn't backup it ;).

Some messages are getting backfilled from telegram chats, then bot freezes and doesn't send messages in any of the ways.

**Comment by JuniorJPDJ** [comment]
the same error persists in 0.11.3+dev.99344c38

**Comment by JuniorJPDJ** [comment]
The issue was with ffmpeg freezing whole bridge after freeze/long converting job. It should probably be handled another way to not block whole thread.

**Comment by Sharparam** [comment]
I seem to be experiencing this issue as well, on version 0.11.3+dev.[e3a067c2](https://github.com/mautrix/telegram/commit/e3a067c27aa3d9dd5e82db307218cc66c8356ddd) (via docker).

The last message to be printed in the log is:

```
[2022-08-20 14:24:53,265] [INFO@telethon.13228400.client.downloads] Starting direct file download in chunks of 65536 at 0, stride 65536
```

Before it freezes and will not process any further events until restarted, and then it freezes again with the same behaviour shortly after the restart, making the bridge unusable.

Looking at the process tree in `htop` shows an ffmpeg process under mautrix-telegram that shows no sign of doing any actual work.

**Comment by chagai95** [comment]
I think I'm facing a similar issue, did you manage to solve this? I don't see how ffmpeg in htop is related to mautrix- telegram but it sounds like the exact problem I'm having...I tried looking the process but it just got started again...I also can't downgrade because I made no recent backup but I think I have a backup from March, maybe I'll try that if there's no other solution...

**Comment by chagai95** [comment]
I disabled backfill and it seems to work fine again 😍

**Comment by verymilan** [comment]
looks like this is the issue i am having as well.. i hope setting the `missed_limit` to `0` really is all it takes to disable it. i at least can confirm that killing the ffmpeg process brings the bridge back to life.

**Comment by verymilan** [comment]
update: disabling backfill only delayed the problem from recurring

**Comment by chagai95** [comment]
So you have the issue again? I haven't had it for a long time

**Comment by verymilan** [comment]
yes, worked right until my second comment ... and so far until now after killing ffmpeg

**Comment by chagai95** [comment]
Ok thx, hope it doesn't come back
