### ISSUE TITLE
M->T: forwarded messages are sent as normal messages for supergroups

### ISSUE THREAD

**Issue by chuangzhu** [mautrix/telegram#818]
The new feature in unreleased v0.12.0

> Added support for bridging forwarded messages as forwards on Telegram.

does not work for supergroups.

I think this is because the `peer_type` of supergroups (i.e. `channel`) is missing in [`mautrix_telegram/portal.py`](https://github.com/mautrix/telegram/blob/master/mautrix_telegram/portal.py#L1954-L1959):

```python
if peer_type == "user" and space != sender.tgid:
    return
dbm = await DBMessage.get_one_by_tgid(TelegramID(msg_id), TelegramID(space))
if dbm and peer_type == "chat" and space != sender.tgid:
    dbm = DBMessage.get_by_mxid(dbm.mxid, dbm.mx_room, sender.tgid)
return dbm
```

**Comment by tulir** [comment]
Works fine for me
