### ISSUE TITLE
Bridge not responding to anything

### ISSUE THREAD

**Issue by chagai95** [mautrix/telegram#830]
These are the debug logs, every time I restart it happens again and I can't seem to understand what the problem is...

[telegram.log](https://github.com/mautrix/telegram/files/9452016/telegram.log)

**Comment by sumnerevans** [comment]
GitHub issues are for bugs in the bridge, not for helping you configure your bridge correctly. Please use the Matrix room for that: https://matrix.to/#/#telegram:maunium.net
