### ISSUE TITLE
Bridge stops working after a random amount of time

### ISSUE THREAD

**Issue by LaT3St** [mautrix/telegram#831]
`mautrix-telegram_1     | [2022-08-31 10:41:27,930] [WARNING@telethon.283411831.network.mtprotostate] Server sent a very new message with ID [PRIVATE?], ignoring`
`mautrix-telegram_1     | [2022-08-31 10:41:27,930] [WARNING@telethon.283411831.network.mtprotosender] Security error while unpacking a received message: Too many messages had to be ignored consecutively`

This happens every time i receive or send a message to Telegram via the bridge.
The bridge just stops working without an apparent reason. This happened a few times now.
The only fix known to me is to delete the database and reconfigure bridging.

I logged out of Telegram via the bot during the debug process. The bot ignores other commands like "help" or "login". If i send "logout" again, the bot responds correctly that I'm not logged in.

**Comment by clown139880** [comment]
same here

**Comment by seiichiro0185** [comment]
Today I updated to Version 0.12.1 of the Bridge (Docker Container) and see the same behaviour. Log messages like described by the OP and the bot is not responding to any commands except logout. It also will print the error message if I type an unknown command, but no valid command does anything.

**Comment by seiichiro0185** [comment]
Update: It seems the Problem in my case was the time of the Server running the bridge. After (re-) activating NTP Timesync on the Server it now works as expected again.

**Comment by LaT3St** [comment]
Thanks for your comment. My bridge works since i did the same to my server.
I've checked the time on the server before resyncing. It was a few seconds behind global time.

I suggest adding some sort of error message at least as a few seconds time difference should not break the whole bridge.
