### ISSUE TITLE
Synchronize Mute and Archived status

### ISSUE THREAD

**Issue by ShadowJonathan** [mautrix/telegram#832]
When using the telegram bridge, im often annoyed i have to double-confirm mute on both telegram and matrix for it to stick, as then i'd get notifications from matrix while i had muted the chat on telegram (often temporarily).

The same applies to Archived/Low Priority status, where I do not want to see chats clogging up the sidebar that i've already archived on telegram.

**Comment by tulir** [comment]
https://github.com/mautrix/telegram/blob/v0.12.0/mautrix_telegram/example-config.yaml#L312-L320
