### ISSUE TITLE
Telegram Saved Messages don't get double-puppeted correctly

### ISSUE THREAD

**Issue by yspreen** [mautrix/telegram#833]
Messages that are sent to that chat from another client will show up on the wrong side. I.e. they'll have my telegram ID as the sender, not my matrix ID.

it also seems that it's impossible to figure out what the currently logged in user's numerical telegram ID is. the ping and the successful login command both don't report that ID. I just get back the username. if there was a command to get the current ID (maybe inside the ping response) it would be easy to work around this

**Comment by tulir** [comment]
That's how saved messages is supposed to work
