### ISSUE TITLE
Cannot get difference since the account is not logged in: SessionRevokedError

### ISSUE THREAD

**Issue by Ulrar** [mautrix/telegram#848]
Hi,

I've just created a telegram account and configured the bridge using the latest docker image, using the latest synapse image as the homeserver.

It works fine for some time (able to talk to people and join rooms), but I randomly get logged out from both the bridge and the Android app every few minutes.
Synapse doesn't show any obvious errors, and the bridge only says this : 

```
[2022-10-03 10:23:43,230] [INFO@telethon.5445146399.client.updates] Getting difference for account updates (seq: 1, pts: 145, qts: 0, date: 2022-10-03 10:19:19+00:00)
[2022-10-03 10:23:43,257] [INFO@telethon.5445146399.client.updates] Cannot get difference since the account is not logged in: SessionRevokedError
```

The server does have ntp enabled and is less than a fraction of a second off, so that shouldn't be the issue.
Not sure what else to look at since there's no other errors logged anywhere, any idea ?
Thanks

**Comment by Ulrar** [comment]
Just to say that this is still an issue, I don't know what I'm doing wrong but the bridge still gets kicked off after a few minutes, which invalidates the session on my Android app as well.
If I leave this bridge off the official app works fine though, so it's something the bridge is doing I guess

**Comment by Ulrar** [comment]
I think I figured it out.
I had blocked IPv6 dns queries (AAAA) in my pi hole to mitigate a bug with something unrelated a while back, and it looks like somehow it was causing this issue. Not sure why it's not falling back to IPv4 like it's supposed to, especially since I don't have IPv6, but there you go. Seems to be working fine now that I pointed it to a different resolver.

**Comment by thedanbob** [comment]
I ran into this same problem trying to use the bridge for the first time. I had to disable it because it kept invalidating all sessions on all my devices.

**Comment by thedanbob** [comment]
Unfortunately it looks like this may not be a bug in the bridge or even the underlying telethon library, but simply an anti-spam measure on the part of Telegram:
https://github.com/LonamiWebs/Telethon/issues/4028
https://github.com/LonamiWebs/Telethon/issues/3999

I tried using the bridge immediately after registering on Telegram and got temporarily banned within minutes. So this is probably just another less stringent restriction.

**Comment by Ulrar** [comment]
So this bridge isn't usable anymore ?

**Comment by tulir** [comment]
The bridge has always worked fine. Telegram doesn't like some accounts and they may need to apply the workarounds mentioned in #733, but that's a bug in the telegram servers.

**Comment by thedanbob** [comment]
I can confirm that #733 helped me, specifically [this comment](https://github.com/mautrix/telegram/issues/733#issuecomment-1175267044). It also might have helped that I left the bridge disabled and just used the official app for a few weeks. Whatever the reason, I haven't been banned / logged out since reenabling the bridge.
