### ISSUE TITLE
Delete 2FA password

### ISSUE THREAD

**Issue by jtagcat** [mautrix/telegram#849]
Like on other bridge's password fields.

**Comment by sumnerevans** [comment]
2FA passwords don't need to be deleted as they are only valid for one login attempt.

**Comment by tulir** [comment]
Telegram has auth factors in the wrong order (one-time code is first factor, password is optional second factor), so the 2FA passwords do need to be deleted

**Comment by tulir** [comment]
Wait, they're already deleted 🤔

**Comment by jtagcat** [comment]
I tested it again, yep it is deleted. ¯\_(ツ)_/¯
