### ISSUE TITLE
Handling of editing replies doesn't conform to the Matrix spec

### ISSUE THREAD

**Issue by q234rty** [mautrix/telegram#851]
When a telegram user edits a reply on the telegram side, the bridge sends a `m.relates_to` like this:
```json
    "m.relates_to": {
      "rel_type": "m.replace",
      "event_id": "<id>",
      "m.in_reply_to": {
        "event_id": "<id>"
      }
    },
```
However https://spec.matrix.org/v1.4/client-server-api/#edits-of-replies specifically says that 
> In contrast to the original reply, there should be no `m.in_reply_to` property in the the `m.relates_to` object

**Comment by tulir** [comment]
This was already fixed
