### ISSUE TITLE
Backfill sends wrong time (origin_server_ts) for my messages only

### ISSUE THREAD

**Issue by Zocker1999NET** [mautrix/telegram#856]
When using "!tg backfill 100" or when the the bot automatically backfills on startup (I configured it), the messages from my partners have the correct `origin_server_ts` from that time. However, my messages have `origin_server_ts` set to the time when the bot backfilled these messages. In Element/SchildiChat, they are still shown in the correct order. See redacted screenshot for an example (the upper message is from my chat partner, the lower from me sent on Telegram before Matrix Bridge was set up; both messages sent on the same day):
![image](https://user-images.githubusercontent.com/1645646/196379528-c9bb9a18-00f3-4dfb-8d2b-f52905ded4f8.png)

**Comment by tulir** [comment]
You shouldn't enable double puppet backfilling unless you configure your homeserver to allow overriding timestamps with double puppeted users.

**Comment by Zocker1999NET** [comment]
okay, can you give me an hint on what I have to enable on Synapse so that may work? support for MSC2716 is already enabled on Synapse, if its that

**Comment by chuckwagoncomputing** [comment]
Did you ever figure this out? I have the same problem.

**Comment by JuniorJPDJ** [comment]
Just disable `backfill.double_puppet_backfill` option in the config. Appservice cannot spoof the sent time when using client endpoints, so it cannot set the time for requests sent by a normal matrix user.

**Comment by phgn0** [comment]
I finally found a fix for the timestamp massaging with puppeteering enabled: you can patch synapse to allow all users to set their own timestamps for sent messages. It's a one line fix: https://github.com/phgn0/synapse/commit/427c931804ad68dda5c7f31ebb228d16088da476

If you're using [spantaleev/matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) to deploy synapse, you can build a fork using these variables:
```
matrix_synapse_version: master
matrix_synapse_container_image_self_build: true
matrix_synapse_container_image_self_build_repo: "https://github.com/phgn0/synapse.git"
```

See https://github.com/mautrix/gmessages/issues/4#issuecomment-1656725849
