### ISSUE TITLE
Can't switch to double puppet

### ISSUE THREAD

**Issue by chr-sy** [mautrix/telegram#859]
Hello!

Trying to switch to double puppet (login-matrix) for an account created a few days ago, I get the following error message:
Unhandled error while handling command:
"mautrix.bridge.custom_puppet.EncryptionKeysFound: The given access token is for a device that has encryption keys set up. Please provide a fresh token, don't reuse one from another client."

Could you please give me some advice how to deal with this error?

Thank you in advance!

**Comment by tulir** [comment]
The error says what's wrong. https://docs.mau.fi/bridges/general/double-puppeting.html has instructions on enabling double puppeting
