### ISSUE TITLE
No way to mute/ban/stop bridging Matrix users from Telegram side

### ISSUE THREAD

**Issue by nuclight** [mautrix/telegram#864]
Observing from Telegram side that @matrix_t2bot floods Telegram chat with messages from Matrix room, neither /help command on bot nor https://t2bot.io/telegram list way how to do ban/kick/mute Matrix user from Telegram side. The only way was for Telegram admin to mute the entire bot.

In fact, this is possible to implement (if not yet, the this is documentation bug) without actual admin rights - e.g. just /mute command (subject to Telegram's admin permissions for issuer) to just "stop bridging this user", without need to ban it from Matrix side.

**Comment by tulir** [comment]
Ban and kick already exist: https://docs.mau.fi/bridges/python/telegram/relay-bot.html#commands

A command to only stop bridging a user is unlikely to happen. A command to mute users on matrix could be added though.

**Comment by nuclight** [comment]
Tried these commands, no reply from bot. Later, seen message from those who've been /mxkick and /mxban - so this don't work.

Also, the commands must be listed in /help and /-completion in Telegram, which is not the case

**Comment by tulir** [comment]
There's no /help command in the bridge and the command completions are set by the bot owner (via t.me/BotFather), not the bridge software. The kick and ban commands were added in v0.12.0, so they won't work if the bridge is out of date.

**Comment by nuclight** [comment]
How to see version? It is @matrix_t2bot in Telegram isn't it yours "official" bot?

**Comment by tulir** [comment]
`!tg version` on the Matrix side shows the version. t2bot.io is not my service.

**Comment by nuclight** [comment]
Well, this shows 0.11.3... Could you please tell name of yours / more recent bot, then?
