### ISSUE TITLE
Two phone number in two different Matrix accounts result in Telegram official client disconnecting

### ISSUE THREAD

**Issue by str0tta** [mautrix/telegram#866]
In my Synapse instance (which is dockerized, I didn't use the official image but I built it from scratch) I have two different Synapse accounts. The first one is used to bridge all my personal chats (on WhatsApp, Telegram, Instagram and Google Chat - every bridged is dockerized as well, and I crafted the image on my own exactly like the Synapse one).
For business (but also personal) needings I created the second account. I also bought a new SIM card which I put in a secondary phone, where I installed WhatsApp and Telegram (both bound to the new SIM card number), so that for emergency reasons people can text me on this new number and I'll always see the notifications (I disabled them on WhatsApp and Telegram official clients to avoid duplicate notifications).
WhatsApp and Google Chat bridges work like a charm. In the second account I have the WhatsApp bridge (mautrix-whatsapp latest binary) set up on the new number, in the Google Chat one I have the second account so that I can, if I want, reply and receive messages both on the "personal" and the "other" Synapse account without any UX loss.
The Telegram bridge, instead, isn't working properly. When I register the second number on Telegram official app, then I receive the token when I `!tg login`, I send the token to the bridge and everything works fine... for no longer than 30 minutes. After this time, the Telegram official client disconnects automatically on my phone, also on the second account I can only receive but not send messages (still on the second account, I didn't ever face an issue on the first number).
During my attempts, I tried to duplicate the bridge configuration and create a separate bridge (same Docker image which is basically python:3.8), changing the minimum required informations such as the telegrambot username, suffixes, so on and so forth. No result.
Then I tried to put another pair of api_id / api_secret, bound, this time, to the new number. No result.
What could I do?

For any question or explanation please don't exitate to ask.

**Comment by tulir** [comment]
It's probably a telegram server bug, there's some discussion in #733
