### ISSUE TITLE
captions not working properly?

### ISSUE THREAD

**Issue by mwelsch** [mautrix/telegram#870]
I am using the latest version of (matrix-docker-ansible-deploy)[https://github.com/spantaleev/matrix-docker-ansible-deploy]. I want to send images using captions. To do so I write to @telegrambot:mydomain something like "caption My test". When actually sending the image it is send with caption, however the "caption" keyword is sent aswell

![image](https://user-images.githubusercontent.com/31733941/203520455-8f2d1632-e676-4859-8036-2965ed42100d.png)

**Comment by tulir** [comment]
You're supposed to use it in the same chat where you send the image and include the `!tg` prefix
