### ISSUE TITLE
Bridge keeps changing power levels of matrix user then kicks them out of the room

### ISSUE THREAD

**Issue by evakdev** [mautrix/telegram#871]
Hello. This happens to some new telegram rooms. The new group appears on matrix, then shows an event saying ' bridge changed the power level of {user} from Default to Custom (95). After minutes, the user is removed from the group, getting the message that the portal is deleted. And then a new group is created. This process keeps repeating over and over and basically makes using the matrix room impossible. I am using Element. I have checked other groups that don't show this problem, and the settings are the same for both groups on Telegram side. The user is not an admin or owner on any of the groups. This leads me to believe it might be the bridge that is faulty, possibly failing to sync power levels properly? Would greatly appreciate it if you could check it out. Thank you :)

**Comment by evakdev** [comment]
any news on this?

**Comment by tulir** [comment]
Bridge logs are generally required to debug anything
