### ISSUE TITLE
Number Banned 

### ISSUE THREAD

**Issue by deetungsten** [mautrix/telegram#878]
Hello,

I'm a US based user and recently added the telegram bridge to my own personal server (local only). I added the telegram account successfully but after 5 min or so, Telegram banned my cellphone number. Any advice on where went wrong? When I generated the api id and token, I left the URL as " ".  Was that a bad decision? In addition, I used login instead of login-qr. 

Thanks!

**Comment by NjlsShade** [comment]
If you used a VoIP number for your telegram account or your account was not "verified" with Telegram then tapping into the API will cause a ban as it trips as being spam automation.

If you reach out to Telegram support they should get you back up and going if you're not already.

**Comment by redthing1** [comment]
I got instabanned for this
