### ISSUE TITLE
Need clarification about "the internal ID" for /pm command

### ISSUE THREAD

**Issue by sitex** [mautrix/telegram#882]
pm <identifier>	Open a private chat with the given Telegram user. identifier is either **the internal ID** ...

What is **the internal ID**?

**Comment by tulir** [comment]
It's the numeric internal user ID, shouldn't need any clarification. Usernames are the primary way to start chats

**Comment by sitex** [comment]
A lot of Telegram users don't have Usernames.

If you don't want to explain. Remove that information from the docs. It's confusing.

**Comment by tulir** [comment]
Good idea, help message has been updated. As for starting chats with users with no username, there are alternative ways mentioned in https://docs.mau.fi/bridges/python/telegram/creating-and-managing-chats.html#private-messages
