### ISSUE TITLE
Issues with Easy Effects + PipeWire

### ISSUE THREAD

**Issue by jazz-it** [mautrix/telegram#883]
When using Telegram on my Manjaro Desktop altogether with **PipeWire** + **Easy Effects** (with some Input effects turned ON, e.g. **Speech Processor**, **Echo Canceller**, **Noise Reduction** and **Pitch**), the voice of the person I'm talking to starts to crackle and become choppy, so I can't understand them at all.
As soon as I disable all the Input effects for my microphone, the communication become flawless again and there's no issue. Other applications ie. web based talk apps or Audacious don't have any issues with such setup.

I'm not sure which logs may help you to diagnose this issue. Please let me know.

**Comment by 9ary** [comment]
You're probably looking for https://github.com/telegramdesktop/tdesktop, this repo is for a Telegram <=> Matrix bridge service.
