### ISSUE TITLE
Automatically add a phone number to your Telegram contacts when pm'ing it

### ISSUE THREAD

**Issue by anoadragon453** [mautrix/telegram#885]
The help text for the `pm` command currently says that a number must first be added to your Telegram contacts before you can use it with the `pm` command:

https://github.com/mautrix/telegram/blob/e655e0a8826eb66e3f133cfe6ab912d275a55715/mautrix_telegram/commands/telegram/misc.py#L135-L143

Is it possible for the bridge to simply automatically add a user to your Telegram contacts?

If a name is also required when adding the contact, perhaps a generated name could be used initially (and then replaced with the Telegram user's username afterwards?).

**Comment by tulir** [comment]
Nowadays it is possible to add individual contacts, previously there was only a mass contact upload call. I think it still needs a name though and there's no way to get the real name of a contact. I guess adding and then deleting the contact might work, but that sounds very hacky

**Comment by anoadragon453** [comment]
Hmm, true. Perhaps we could just add a `add-contact` command which takes a name, and poke the user to use it first if they attempt to pm a number that's not yet in their contacts.
