### ISSUE TITLE
Media from Telegram are uploaded to homeserver media-store instead of matrix-media-repo

### ISSUE THREAD

**Issue by tux93** [mautrix/telegram#893]
I have set up the bridge in combination with dendrite and matrix-media-repo, both are reverse-proxied through nginx as per their documentation:
```
upstream monolith {
  server 127.0.0.1:8008;
}
upstream mediarepo {
  server 127.0.0.1:42666;
  # This is a workaround for the media ending up in the wrong store:
  # fall back to dendrite on 404
  server 127.0.0.1:8008;
}
server {
[...]
   location ~ ^/_matrix/(media|client/v3/logout) {
    proxy_set_header Host $domain;
    proxy_hide_header Cache-Control;
    proxy_ignore_headers Cache-Control;
    proxy_next_upstream http_404;
    proxy_pass http://mediarepo;
  }
  location ~ /_(matrix|synapse|dendrite) {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    proxy_pass http://monolith;
  }
[...]
}
```

The bridge is configured to connect to the homeserver through nginx:
```
homeserver:
    address: https://matrix.$domain
    domain: $domain
[...]
```

Despite this media bridged from Telegram are uploaded to the media-store of dendrite instead of matrix-media-repo.

**Comment by tulir** [comment]
Probably not related to the bridge

**Comment by tux93** [comment]
Okay, do you think the issue is with matrix-media-repo or dendrite then?

**Comment by tux93** [comment]
I did remove the fallback and at least now nothing gets added to the homeserver store anymore, of course now I have the issue that Telegram Avatars 404 because they ended up in the homeserver store.

Is there a way to force a re-sync of puppet profiles from Telegram?
