### ISSUE TITLE
rooms bridged to Telegram keep getting deleted and recreated, room ID changes all the time

### ISSUE THREAD

**Issue by evakdev** [mautrix/telegram#894]
### Issue

The issue is with my telegram rooms in matrix. Some of them (not all) keep getting closed and recreated everyday. The messages are synced, but the room id changes every time. The id change prevents me from being able to identify rooms in my project, and sometimes creates unnecessary notifications. In addition, any alias I had set for the room is no longer present on the new room. 
This happens at least once a day, sometimes more. 

I’ve checked the perms on both “healthy” (not getting recreated everyday) and problematic rooms in telegram, and haven’t been able to find any specific situation that would make these rooms unique. It seems to be completely random. Sometimes problematic rooms suddenly become healthy, and sometimes a room that was okay becomes faulty. Sometimes the rooms get recreated on their own, and sometimes I have to manually sync them by sending the “sync” command to the bridge. I can't figure out what's causing it.

### Expectation 
To find out what is causing this, and figure it how to prevent the room ID from changing. Since the ID is what every single one of API endpoints work with, I need it to not stay unique and reliable, just as Whatsapp rooms are. 

### System
I am using Element One as my server and use the telegram bridge hosted there.

### Logs
Here are the [debug logs](https://github.com/mautrix/telegram/files/10777337/rageshake.zip) provided to me by Element Web. Since I don't have admin access to the homeserver, this is all the debug logs I've got. Hopefully its enough. 

I would greatly appreciate anything that can help me figure this out. 
Thank you in advance for your help.

**Comment by evakdev** [comment]
Hey thanks for the response. I've already contacted Element support but haven't received a reply. I have created the issue on the element fork too. Since the base bridge is the same, I thought maybe someone working on the original repo could have an idea what the issue could be. If you even have any guesses, it can help a lot :)

**Comment by evakdev** [comment]
Also, is there an endpoint to get a list of all rooms along with their display names from the bot? If so, that could help too.

**Comment by LocalMonero** [comment]
@tulir we're experiencing the same issue. 

This is triggered by any restart of the mautrix-telegram service. Some perfectly OK existing portals are deleted, matrix users are kicked, and new empty rooms with no history or puppet members are created and re-bridged, forcing the matrix user to manually rejoin of the old portal room that's available in Element's "historical rooms" section, which is no longer bridged, so the mautrix-telegram admin needs to redo the bridging process. 

This doesn't happen for all portals but a specific subset which is the same every restart. It's extremely annoying and necessitates a `!tg bridge <id>` `!tg delete-and-continue` in the room that used to be the old portal room that you need to rejoin by opening it from the "historical rooms" section every time the service is restarted. We've been experiencing this issue for a relatively long time now (months at least).

Here are the logs from the service's restart:
[mautrix-telegram-recreating-unneeded-portals-logs.txt](https://github.com/mautrix/telegram/files/10789465/mautrix-telegram-recreating-unneeded-portals-logs.txt)

Note the last line of those logs, which shows that it's deleting a portal, the room mxid matches the "old" portal room which shouldn't be deleted but just kept as is. There are no logs afterwards of any interest (just failed message handling which happens a minute later).

**Comment by LocalMonero** [comment]
Thanks for fixing ♥

**Comment by evakdev** [comment]
Thank you for the fix!
