### ISSUE TITLE
Reverse puppet randomly joining channel discussion chats

### ISSUE THREAD

**Issue by Astrrra** [mautrix/telegram#896]
When having a telegram account linked to the bridge for puppeting via matrix, it sometimes randomly joins channel discussion chats. This happens after each comment (which is understandable, but still pretty annoying), but about twice a day (in my experience) it joins a random discussion chat without any input from my side. This **usually** happens when the channel posts something, but this definitely **doesn't happen every time** the channel posts something, just once in a while. This is very annoying and often makes for awkward situations :(

**Comment by NotSociallyFit** [comment]
Same stuff, apparently it even applies to join invite only groups

**Comment by Astrrra** [comment]
Hello again! I've updated to 0.14, and the issue is unfortunately still there. Is there any way I can help in diagnosing it?

Also, maybe the "join the discussion chat after sending a comment to it in telegram" behaviour deserves a toggle in the config? I use the matrix bridge and the native clients interchangeably, and often just want to comment on one specific channel post without joining the chat. Right now, I have to manually leave that chat after commenting, which also disables all the reply notifications...
