### ISSUE TITLE
security error while unpacking a received message too many messages had to be ignored consecutively

### ISSUE THREAD

**Issue by arkadym** [mautrix/telegram#905]
Yesterday started see this error in log, bridge is totaly not working, even ping command do nothing
![image](https://user-images.githubusercontent.com/7422012/230560155-82df2897-3bc1-49b7-9c57-c74131787595.png)

**Comment by tmkis2** [comment]
Had the same here - check your server time. You may need to set it with ntp(date) - I had a time difference of about 30s - after fixing this everything worked again

**Comment by arkadym** [comment]
@tmkis2 thank you! can close ticker.
