### ISSUE TITLE
Main Telegram client gets logged out of sessions shortly after successfully joining Telegram bridge

### ISSUE THREAD

**Issue by tquest1** [mautrix/telegram#911]
I have successfully set up a Synapse server with Telegram/Signal/Whatsapp bridges. I am able to connect my Telegram account using the telegrambot successfully & receive messages. After some time my main Android client gets logged out automatically.  I log back in, then reconnect the telegrambot in the bridge, it works fine, then after some time I get logged out again on the Android client.

Any ideas what's happening. I installed matrix using the matrix-docker-ansible-deploy ansible method & my vars.yml is contains:

```matrix_mautrix_telegram_enabled: true
matrix_mautrix_telegram_api_id: redacted
matrix_mautrix_telegram_api_hash: redacted
matrix_mautrix_telegram_configuration_extension_yaml: |
  bridge:
    permissions:
      'redacted': admin
matrix_mautrix_telegram_login_shared_secret: redacted
matrix_mautrix_telegram_configuration_extension_yaml: |
  bridge:
    encryption:
      allow: true
      default: true

**Comment by tulir** [comment]
#733
