### ISSUE TITLE
Monospace link

### ISSUE THREAD

**Issue by opk12** [mautrix/telegram#913]
A Matrix monospace link is not a link on Telegram. For example, I type this in Element, but it is not clickable in Telegram.

    text [`caption`](https://example.org)

**Comment by tulir** [comment]
Telegram doesn't allow monospace links

**Comment by opk12** [comment]
Ah that's unfortunate. Can the URL be preserved?
* link without monospace: text [caption](https://example.org)
* URL after the caption: text `caption` https://example.org

Use cases:
- when quoting from an online article, I naturally highlight the quote as monospace + link
- OpenStreetMap (the free-licensed Wikipedia of maps) is a NoSql database and people like to highlight the key-value mapping with monospace (because it's code) + link to the documentation (from the OpenStreetMap wiki).
