### ISSUE TITLE
Sending PM by client's Telegram ID

### ISSUE THREAD

**Issue by sitex** [mautrix/telegram#917]
Hello. Thank you for your work.

After the connection to my Telegram number was lost, I found myself without access to previous chats and contacts. This meant losing not only the chat history but also the ability to reach out to those contacts unless they were saved in my contact book.

Fortunately, I had saved the Telegram IDs of my contacts. Now, the question was how to utilize them with the mautrix/telegram bridge.

Considering that there are Telegram bots capable of initiating a chat with a user based on their Telegram ID, I speculated that it should be feasible to incorporate such a feature into the mautrix/telegram bridge.

Thank you

**Comment by tulir** [comment]
Neither bots nor real users can start chats with just the internal numeric user ID, you always need the access hash too (which is specific to your account). Access hashes are managed automatically (stored as soon as the bridge first sees them), there's currently no way to supply access hashes manually other than modifying the database. If you actually meant username, then that can of course be used to find users. The `pm` command accepts both usernames and internal user IDs.
