### ISSUE TITLE
Debug info in the fallback message

### ISSUE THREAD

**Issue by opk12** [mautrix/telegram#937]
We got the fallback message in our community chat today (`This message is not supported on your version of Mautrix-Telegram`). Is it possible to add debug info, maybe hidden in the JSON?
* To understand what feature to request.
* To decide how much important the message is and how to react, without annoying people (asking for clarification) and the chat (making an off-topic for a bridging issue). For example, I can let go a new kind of sticker, but I'd rather request that people avoid a new kind of text message.

**Comment by tulir** [comment]
No, it just means Telegram sent a `messageMediaUnsupported` object, which has no additional information
