### ISSUE TITLE
Bridge reactions from Telegram with bot accounts

### ISSUE THREAD

**Issue by kuba-orlik** [mautrix/telegram#952]
As it is now possible to read reactions via the Telegram bot API:

https://core.telegram.org/bots/api#december-29-2023

**Comment by tulir** [comment]
Reactions are already bridged and the bridge doesn't use the bot API

**Comment by kuba-orlik** [comment]
Oh I get it- so I haven't seen the reactions being bridged because I use a bot account. Thank you for the clarification and updating the title of the issue :+1:
