### ISSUE TITLE
Sync Telegram bot messages to matrix room 

### ISSUE THREAD

**Issue by Kabyss** [mautrix/telegram#956]
Messages sent by Telegram bots in Telegram chats are not synced to Matrix rooms, which appears to be a limitation of the Telegram bot API. It's along the lines of 'bots cannot see messages sent by other bots.' Is there no other way to achieve this? I have noticed Telegram userbots where many things can be automated using a normal user account and string session. Can this not be used to create bridges that can sync all messages, whether sent by a bot or a user?

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/python/telegram/authentication.html
