### ISSUE TITLE
Telegram bridge bot not responding to messages in matrix room?

### ISSUE THREAD

**Issue by mhfowler** [mautrix/telegram#958]
I've tried to setup a mautrix-telegram bot on yunohost. The install seemed to work well and I'm able to send messages directly to the telegram bridge bot user and they respond to commands and show that the bot is successfully logged in to telegram.

The bot also joins a matrix room when invited, and sends a first message, but when I send messages in that room via
```!tg help```
or other variations I've tried it never responds (and in element, it says the message is not seen, which I wonder if its relevant). 

I've tried making a public room and a private room, both without encryption.

Here is a screenshot of the successful communication directly with the bot user:
![Screenshot from 2024-03-26 15-52-55](https://github.com/mautrix/telegram/assets/1831536/74a5e9b1-7856-435b-8528-f503a412f989)

And here is a screenshot of successfully inviting the bot to a room, but it not responding to !tg commands:
![Screenshot from 2024-03-26 15-52-26](https://github.com/mautrix/telegram/assets/1831536/8d18f67f-f305-4af3-9531-81ace56f59fe)

I wonder if I'm missing something? Or am not sending the commands in the correct format? Any help appreciated. I want to tell the bot to bridge a particular room.

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/general/troubleshooting.html
