### ISSUE TITLE
Replies to image captions are not handled correctly

### ISSUE THREAD

**Issue by divadsn** [mautrix/telegram#969]
When someone sends a picture with a text caption from Telegram, the message is bridged to Matrix as two separate messages:

![360465549-bee93b89-1cbe-4d70-8fdc-00ea904189ed](https://github.com/user-attachments/assets/2d9269e0-a764-4889-ad3e-3521b0af68f6)

However, when someone replies to the text caption, the reply is not sent properly to the original message on Telegram:

![image](https://github.com/user-attachments/assets/fd15fb6c-6980-4b1f-95d8-e930654682e7)

**Comment by sumnerevans** [comment]
Captions will be inline using [MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530) in the Go rewrite of the bridge and thus will not have this problem.
