### ISSUE TITLE
Image captions are not deleted when someone deletes an image on Telegram

### ISSUE THREAD

**Issue by divadsn** [mautrix/telegram#970]
Similarly to #969, when a user deletes an image with a caption on Telegram, only the image gets deleted on Matrix:

![photo_2024-08-22_16-06-48](https://github.com/user-attachments/assets/1ca5246b-4b8e-4fdf-8b58-e1e024b5f5ca)

**Comment by sumnerevans** [comment]
Captions will be inline using [MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530) in the Go rewrite of the bridge and thus will not have this problem.
