### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by anylayer** [mautrix/telegram#983]
`self.app.router.add_route("GET", f"{portal_prefix}", self.get_portal_by_mxid)
self.app.router.add_route("GET", "/v1/portal/{tgid:-[0-9]+}", self.get_portal_by_tgid)`
需要调整这两个路由的顺序，否则无法根据群聊id获取portal

**Comment by tulir** [comment]
The legacy provisioning API will be deprecated after the switch to megabridge, so old endpoints won't be fixed at this point.

**Comment by anylayer** [comment]
> The legacy provisioning API will be deprecated after the switch to megabridge, so old endpoints won't be fixed at this point.

megabridge?
